identifier = "braindance_protocol"
display_name = "Braindance Protocol"
creator = "osulli"
description = "A collection of LUA scripts to modify your Cyberpunk 2077 experience"
version = "0.1.0"
license = "GNU GPL V3"
